FROM meltano/meltano:latest

WORKDIR /project

# COPY ./requirements.txt .
# RUN pip install -r requirements.txt

# COPY ./meltano.yml .
# RUN meltano install

# COPY . .

RUN ["python", "--version"]

# EXPOSE 8080

# RUN ["meltano", "init", "alpha"]
